### PR TITLE
Support for account with no payment methods #163

### PR DESCRIPTION
**Pull request by javier-gomez-hs**
- Updated deletePaymentMethod with new property forceDefaultPaymentMethodDeletion

### CODE REVIEW

**Comment by pierre** [comment]
👍 but PR needs to be against the `work-for-release-0.17.x` branch.

**Comment by javier-gomez-hs** [comment]
@pierre 
Sure! Unfortunately I can't delete this PR or edit it (I don't have permissions), so maybe you can move it to **work-for-release-0.17.x**?

Thanks!

**Comment by sbrossie** [comment]
@javier-gomez-hs I 'll care of the merge (in the right branch) when the feature is ready (waiting for [PR 571](https://github.com/killbill/killbill/pull/571)) to be completed.

**Comment by sbrossie** [comment]
Duplicate of [PR 17](https://github.com/killbill/killbill-api/pull/17), resubmitted against correct target branch.

**Pull request closed without merging**
