### PR TITLE
changing Boolean type

### PR DESCRIPTION
**Pull request by matias-aguero-hs**

### CODE REVIEW

**Comment by pierre** [comment]
Why the change? This doesn't seem consistent with the other setters.

**Comment by matias-aguero-hs** [comment]
to be able to allow null values on that column for regular accounts.

**Comment by pierre** [comment]
Couldn't we use the default value `false` in that case?

It seems consistent (payments are not delegated since there is no parent) and it avoids the potential issue of passing an ambiguous `null` value for an account with a parent.

**Comment by matias-aguero-hs** [comment]
sounds like a  plan! :+1:

**Pull request merged**
